/**
 * v0.43.0 — server/tools/apply-spec-gen.test.ts
 *
 * Coverage:
 *   - AC-5 v0.42.0 no-overwrite invariant inherits via reuse on the
 *     caller-action path (empty / all-(none) sections → file bytes
 *     unchanged + `spec-gen-empty-sections` warning surfaces).
 *   - AC-5 Zod input validation rejects malformed payloads before any
 *     merge work happens (file bytes unchanged).
 *   - AC-6 race-window: hand-author marker that LANDED on disk between
 *     brief-emit and merge time is preserved; the caller's content for
 *     OTHER sub-sections still overwrites.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdtempSync,
  rmSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  readdirSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { handleApplySpecGen, applySpecGenInputSchema } from "./apply-spec-gen.js";
import { z } from "zod";

function sha256(buf: string): string {
  return createHash("sha256").update(buf).digest("hex");
}

function readSpec(tmp: string): string {
  return readFileSync(join(tmp, "docs", "generated", "TECHNICAL-SPEC.md"), "utf-8");
}

/**
 * v0.43.2 (I1 fold) — seed a fake brief-emit run record under .forge/runs/
 * so handleApplySpecGen's pre-validation probe finds it. Without this, the
 * pre-validation returns isError before any merge work happens.
 */
function seedRunRecord(tmp: string, runId: string): void {
  const runsDir = join(tmp, ".forge", "runs");
  mkdirSync(runsDir, { recursive: true });
  const filename = `forge_evaluate-2026-05-11T20-00-00-000Z-${runId}.json`;
  writeFileSync(
    join(runsDir, filename),
    JSON.stringify({ tool: "forge_evaluate", runId }, null, 2),
    "utf-8",
  );
}

/**
 * Seed a TECHNICAL-SPEC.md with one story section. Used by AC-5 and AC-6
 * to verify the preserve-invariant + hand-author race-window guard.
 */
function seedTechSpec(tmp: string, opts: { handAuthored?: boolean } = {}): void {
  const dir = join(tmp, "docs", "generated");
  mkdirSync(dir, { recursive: true });
  const apiContractsBody = opts.handAuthored
    ? "<!-- hand-authored 2026-05-11 by operator -->\n- `someApi`: hand-written contract"
    : "- `someApi`: prior-generated bullet";
  const body = [
    "<!-- agent-first: this file is auto-regenerated by forge-harness on every story PASS. -->",
    "<!-- Source of truth: docs/decisions/<US-NN>/*.md (ADRs) and docs/generated/<US-NN>.md (TECHNICAL-SPEC). -->",
    "<!-- Do not hand-edit; edits are overwritten on next regeneration. -->",
    "<!-- Regeneration tool: forge-harness `forge_evaluate` (PASS verdict path). -->",
    "<!-- Design rationale: P60 Build for Consumer, Not Author. -->",
    "",
    "> Generated by forge-harness on 2026-05-11.",
    "",
    "---",
    'schemaVersion: "1.0.0"',
    'lastUpdated: "2026-05-11T00:00:00.000Z"',
    "stories:",
    '  - id: "US-01"',
    '    lastUpdated: "2026-05-11T00:00:00.000Z"',
    '    lastGitSha: "unknown"',
    "---",
    "",
    "## story: US-01",
    "",
    "### api-contracts",
    "",
    apiContractsBody,
    "",
    "### data-models",
    "",
    "- `SomeShape`: prior data model bullet",
    "",
    "### invariants",
    "",
    "- prior invariant bullet",
    "",
    "### test-surface",
    "",
    "- prior test bullet",
    "",
  ].join("\n");
  writeFileSync(join(dir, "TECHNICAL-SPEC.md"), body, "utf-8");
}

// ── Zod input-validation tests (AC-5 malformed-input case) ────────────

describe("forge_apply_spec_gen — Zod input validation (AC-5)", () => {
  it("rejects missing sections.invariants before reaching merge code", () => {
    const schema = z.object(applySpecGenInputSchema);
    const malformed = {
      runId: "abcd",
      storyId: "US-01",
      projectPath: "/tmp/x",
      sections: {
        "api-contracts": "x",
        "data-models": "x",
        // invariants intentionally missing
        "test-surface": "x",
      },
      contracts: [],
      tokens: { inputTokens: 0, outputTokens: 0 },
    };
    const result = schema.safeParse(malformed);
    expect(result.success).toBe(false);
  });

  it("rejects runId that isn't 4-char hex", () => {
    const schema = z.object(applySpecGenInputSchema);
    const malformed = {
      runId: "not-hex",
      storyId: "US-01",
      projectPath: "/tmp/x",
      sections: {
        "api-contracts": "x",
        "data-models": "x",
        invariants: "x",
        "test-surface": "x",
      },
      contracts: [],
      tokens: { inputTokens: 0, outputTokens: 0 },
    };
    const result = schema.safeParse(malformed);
    expect(result.success).toBe(false);
  });

  it("accepts a well-formed payload", () => {
    const schema = z.object(applySpecGenInputSchema);
    const wellFormed = {
      runId: "a1b2",
      storyId: "US-01",
      projectPath: "/tmp/x",
      sections: {
        "api-contracts": "(none)",
        "data-models": "(none)",
        invariants: "(none)",
        "test-surface": "(none)",
      },
      contracts: [],
      tokens: { inputTokens: 0, outputTokens: 0 },
    };
    const result = schema.safeParse(wellFormed);
    expect(result.success).toBe(true);
  });

  it("accepts an optional tokensEstimated: true field (v0.45.0)", () => {
    const schema = z.object(applySpecGenInputSchema);
    const withEstimate = {
      runId: "a1b2",
      storyId: "US-01",
      projectPath: "/tmp/x",
      sections: {
        "api-contracts": "(none)",
        "data-models": "(none)",
        invariants: "(none)",
        "test-surface": "(none)",
      },
      contracts: [],
      tokens: { inputTokens: 100, outputTokens: 50 },
      tokensEstimated: true,
    };
    const result = schema.safeParse(withEstimate);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.tokensEstimated).toBe(true);
    }
  });
});

// ── AC-5: preserve-invariant (empty/all-none sections → bytes unchanged) ──

describe("forge_apply_spec_gen — AC-5 v0.42.0 preserve-invariant", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-"));
    seedTechSpec(tmp, {});
    seedRunRecord(tmp, "abcd");
  });
  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("all-(none) sections → spec bytes UNCHANGED + spec-gen-empty-sections warning", async () => {
    const before = readSpec(tmp);
    const beforeSha = sha256(before);
    const result = await handleApplySpecGen({
      runId: "abcd",
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "(none)",
        "data-models": "(none)",
        invariants: "(none)",
        "test-surface": "(none)",
      },
      contracts: [],
      tokens: { inputTokens: 0, outputTokens: 0 },
    });
    expect(result.isError).toBeUndefined();
    const after = readSpec(tmp);
    const afterSha = sha256(after);
    expect(afterSha).toBe(beforeSha);
    // Warning surfaces on the response payload.
    const body = JSON.parse(result.content[0].text) as {
      warnings: Array<{ kind: string }>;
    };
    const kinds = body.warnings.map((w) => w.kind);
    expect(kinds).toContain("spec-gen-empty-sections");
  });

  it("empty-string sections → also preserves bytes (same path)", async () => {
    const before = readSpec(tmp);
    const beforeSha = sha256(before);
    await handleApplySpecGen({
      runId: "abcd",
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "",
        "data-models": "",
        invariants: "",
        "test-surface": "",
      },
      contracts: [],
      tokens: { inputTokens: 0, outputTokens: 0 },
    });
    const after = readSpec(tmp);
    expect(sha256(after)).toBe(beforeSha);
  });
});

// ── AC-6: hand-author race-window preservation ────────────────────────

describe("forge_apply_spec_gen — AC-6 hand-author race-window guard", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-"));
    // Seed WITH a hand-authored api-contracts section. The other three
    // sub-sections are NOT hand-authored — the caller's content for those
    // should overwrite while api-contracts stays preserved.
    seedTechSpec(tmp, { handAuthored: true });
    // v0.43.2 (I1 fold) — seed brief-emit run record so pre-validation passes.
    // The AC-14 sub-test re-creates tmp from scratch and generates its own
    // runId via handleEvaluate, so it doesn't depend on this seed.
    seedRunRecord(tmp, "abcd");
  });
  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("AC-14: brief-emit + merge events share one run-record file (atomic observability)", async () => {
    // This test imports the real (unmocked) `handleEvaluate` and
    // `handleApplySpecGen` and asserts both events land in the SAME
    // `.forge/runs/forge_evaluate-{timestamp}-{runId}.json` file.
    //
    // The seeded TECHNICAL-SPEC.md does NOT have a hand-author marker on
    // this test's project path (we re-seed without it), so the directive
    // flow runs end-to-end: brief emit → caller-side merge → same record.
    rmSync(tmp, { recursive: true, force: true });
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-ac14-"));
    seedTechSpec(tmp, { handAuthored: false });
    // Write a plan file the evaluator can load.
    const plan = {
      schemaVersion: "3.0.0",
      stories: [
        {
          id: "US-01",
          title: "Story 1",
          acceptanceCriteria: [
            { id: "AC-01", description: "echo ok", command: "echo ok" },
          ],
        },
      ],
    };
    writeFileSync(join(tmp, "plan.json"), JSON.stringify(plan), "utf-8");

    // Force the directive flow (default) for this test.
    process.env.FORGE_SPEC_CALLER_ACTION = "";
    delete process.env.FORGE_SPEC_CALLER_ACTION;

    // Drive forge_evaluate. Story-mode runs the AC shell command (`echo ok`)
    // which passes deterministically; the PASS path emits the directive.
    const { handleEvaluate } = await import("./evaluate.js");
    const evalResp = await handleEvaluate({
      evaluationMode: "story",
      storyId: "US-01",
      planPath: join(tmp, "plan.json"),
      projectPath: tmp,
    });
    expect(evalResp.isError).toBeUndefined();
    expect(evalResp.callerAction).toBe("generate-spec-inline");
    const brief = evalResp.specGenBrief!;
    expect(brief.runId).toMatch(/^[0-9a-f]{4}$/);

    // Drive forge_apply_spec_gen with the briefer's runId + caller content.
    const applyResp = await handleApplySpecGen({
      runId: brief.runId,
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "- `myApi`: caller-generated bullet",
        "data-models": "- `MyShape`: caller-generated bullet",
        invariants: "- caller-generated invariant",
        "test-surface": "- caller-generated test",
      },
      contracts: ["forge_evaluate"],
      tokens: { inputTokens: 100, outputTokens: 50 },
    });
    expect(applyResp.isError).toBeUndefined();

    // Assert: both events land in the SAME record file. The filename suffix
    // is the runId.
    const runsDir = join(tmp, ".forge", "runs");
    const entries = readdirSync(runsDir) as string[];
    const recordFile = entries.find(
      (e) => e.startsWith("forge_evaluate-") && e.endsWith(`-${brief.runId}.json`),
    );
    expect(recordFile).toBeDefined();
    const record = JSON.parse(
      readFileSync(join(runsDir, recordFile!), "utf-8"),
    ) as {
      generatedDocs?: {
        specPath?: string;
        specGenMode?: string;
        contracts?: string[];
      };
      evalReport?: unknown;
    };
    // The brief-emit event wrote `evalReport`, the merge event overwrote
    // `generatedDocs` with the post-merge envelope (specPath set, contracts
    // populated, specGenMode flipped to "caller-action").
    expect(record.evalReport).toBeDefined();
    expect(record.generatedDocs).toBeDefined();
    expect(record.generatedDocs!.specPath).toContain("TECHNICAL-SPEC.md");
    expect(record.generatedDocs!.specGenMode).toBe("caller-action");
    expect(record.generatedDocs!.contracts).toEqual(["forge_evaluate"]);
  });

  it("v0.45.0: tokensEstimated: true threads onto generatedDocs.tokensEstimated", async () => {
    // Caller-action path where the caller (e.g. /forge-execute v1.1.0)
    // estimates tokens via byte/4 and marks them as approximate. The flag
    // must land on the run record's generatedDocs envelope so cost-audit
    // consumers can mark the totalCostUsd as estimated.
    rmSync(tmp, { recursive: true, force: true });
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-tokens-est-"));
    seedTechSpec(tmp, { handAuthored: false });
    seedRunRecord(tmp, "abcd");

    const applyResp = await handleApplySpecGen({
      runId: "abcd",
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "- `est`: caller bullet",
        "data-models": "- `Est`: caller bullet",
        invariants: "- caller invariant",
        "test-surface": "- caller test",
      },
      contracts: [],
      tokens: { inputTokens: 1000, outputTokens: 500 },
      tokensEstimated: true,
    });
    expect(applyResp.isError).toBeUndefined();

    const runsDir = join(tmp, ".forge", "runs");
    const entries = readdirSync(runsDir) as string[];
    const recordFile = entries.find((e) => e.endsWith("-abcd.json"));
    expect(recordFile).toBeDefined();
    const record = JSON.parse(
      readFileSync(join(runsDir, recordFile!), "utf-8"),
    ) as { generatedDocs?: { tokensEstimated?: boolean } };
    expect(record.generatedDocs?.tokensEstimated).toBe(true);
  });

  it("v0.45.0: tokensEstimated unset → field absent from generatedDocs (backwards compat)", async () => {
    rmSync(tmp, { recursive: true, force: true });
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-no-est-"));
    seedTechSpec(tmp, { handAuthored: false });
    seedRunRecord(tmp, "abcd");

    const applyResp = await handleApplySpecGen({
      runId: "abcd",
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "- `m`: caller bullet",
        "data-models": "- `M`: caller bullet",
        invariants: "- caller invariant",
        "test-surface": "- caller test",
      },
      contracts: [],
      tokens: { inputTokens: 100, outputTokens: 50 },
      // tokensEstimated intentionally omitted (default = measured tokens)
    });
    expect(applyResp.isError).toBeUndefined();

    const runsDir = join(tmp, ".forge", "runs");
    const entries = readdirSync(runsDir) as string[];
    const recordFile = entries.find((e) => e.endsWith("-abcd.json"));
    expect(recordFile).toBeDefined();
    const record = JSON.parse(
      readFileSync(join(runsDir, recordFile!), "utf-8"),
    ) as { generatedDocs?: { tokensEstimated?: boolean } };
    expect(record.generatedDocs?.tokensEstimated).toBeUndefined();
  });

  it("preserves hand-authored sub-section AND overwrites the other three", async () => {
    const beforeBody = readSpec(tmp);
    // Sanity: the hand-author marker is in the seeded file.
    expect(beforeBody).toContain("<!-- hand-authored 2026-05-11 by operator -->");

    await handleApplySpecGen({
      runId: "abcd",
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts":
          "- `newApi`: this should NOT land because the sub-section is hand-authored",
        "data-models": "- `NewShape`: caller-generated, SHOULD land",
        invariants: "- caller-generated invariant, SHOULD land",
        "test-surface": "- caller-generated test bullet, SHOULD land",
      },
      contracts: [],
      tokens: { inputTokens: 100, outputTokens: 50 },
    });

    const afterBody = readSpec(tmp);
    // Hand-authored bullet preserved.
    expect(afterBody).toContain("<!-- hand-authored 2026-05-11 by operator -->");
    // The caller's api-contracts content was NOT written.
    expect(afterBody).not.toContain(
      "- `newApi`: this should NOT land because the sub-section is hand-authored",
    );
    // The other three sub-sections WERE overwritten with caller content. Note:
    // the no-vocabulary post-validator path keeps the bullets unchanged when
    // no source vocabulary can be built (empty affectedPaths) — so caller
    // bullets land verbatim.
    expect(afterBody).toContain("caller-generated invariant, SHOULD land");
    expect(afterBody).toContain("caller-generated test bullet, SHOULD land");
    // The body changed (despite api-contracts being preserved verbatim) because
    // the other three sub-sections changed.
  });
});

// ── v0.43.2 (I1 fold) — runId pre-validation (nonexistent runId case) ───

describe("forge_apply_spec_gen — v0.43.2 runId pre-validation (I1 fold)", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-v0432-"));
    seedTechSpec(tmp, {});
    // INTENTIONALLY DO NOT seed a brief-emit run record — the pre-validation
    // probe should fail before any spec mutation happens.
  });
  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("syntactically-valid but nonexistent runId returns isError + leaves spec bytes unchanged", async () => {
    const before = readSpec(tmp);
    const beforeSha = sha256(before);

    const result = await handleApplySpecGen({
      runId: "dead", // 4-char hex, Zod-valid, but no brief-emit record exists
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "- `newApi`: caller content that should NOT land",
        "data-models": "- `NewShape`: caller content that should NOT land",
        invariants: "- caller invariant that should NOT land",
        "test-surface": "- caller test that should NOT land",
      },
      contracts: [],
      tokens: { inputTokens: 100, outputTokens: 50 },
    });

    // Pre-validation fired: isError set, error text mentions the missing record.
    expect(result.isError).toBe(true);
    expect(result.content[0].text).toContain(
      "no brief-emit run record found for runId=dead",
    );

    // Spec file bytes unchanged — the spec mutation never happened.
    const after = readSpec(tmp);
    expect(sha256(after)).toBe(beforeSha);
  });

  it(".forge/runs/ directory entirely missing → same isError path", async () => {
    // Re-create tmp without the .forge/runs/ dir at all.
    rmSync(tmp, { recursive: true, force: true });
    tmp = mkdtempSync(join(tmpdir(), "forge-apply-spec-gen-v0432-noruns-"));
    seedTechSpec(tmp, {});
    // Deliberately do NOT create .forge/runs/.

    const before = readSpec(tmp);
    const beforeSha = sha256(before);

    const result = await handleApplySpecGen({
      runId: "abcd",
      storyId: "US-01",
      projectPath: tmp,
      sections: {
        "api-contracts": "(none)",
        "data-models": "(none)",
        invariants: "(none)",
        "test-surface": "(none)",
      },
      contracts: [],
      tokens: { inputTokens: 0, outputTokens: 0 },
    });

    expect(result.isError).toBe(true);
    expect(result.content[0].text).toContain("no brief-emit run record found for runId=abcd");
    const after = readSpec(tmp);
    expect(sha256(after)).toBe(beforeSha);
  });
});
