/**
 * adr-extractor.ts — synchronous post-PASS canonicaliser of subagent-written
 * Architecture Decision Record stubs.
 *
 * v0.36.0 Phase C (improvement #4). Called from `server/tools/evaluate.ts`
 * IMMEDIATELY AFTER the spec-generator and IMMEDIATELY BEFORE
 * `writeRunRecord` on a story-mode PASS. The call is sequenced this way so
 * `RunRecord.generatedDocs.adrPaths` carries the canonicalised paths without
 * a second journal write.
 *
 * Unlike `spec-generator.ts`, this module is **deterministic** — it does NOT
 * call an LLM. The implementing subagent (spawned via /forge-execute) decides
 * which decisions are material and writes one stub per decision into
 * `.forge/staging/adr/<storyId>/`. This module's job is purely
 * canonicalisation: assign monotonic numbers, copy stubs to the canonical
 * `docs/decisions/` location with full front-matter, delete staging, rebuild
 * `INDEX.md` from scratch.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * STAGING SCHEMA (subagent → adr-extractor contract)
 * ──────────────────────────────────────────────────────────────────────────
 *
 * Path: `.forge/staging/adr/<storyId>/<short-slug>.md`
 *
 * Required YAML front-matter (all fields, in any order):
 *   ---
 *   title: "<one-line decision title>"
 *   story: "<storyId>"           # MUST match the directory's storyId
 *   context: "<short context>"   # one paragraph, may use \n for line breaks
 *   decision: "<short decision>" # one paragraph
 *   consequences: "<short consequences>"
 *   alternatives: "<short alternatives>"  # may be a markdown bullet list
 *   ---
 *
 * Body after the front-matter is IGNORED — the extractor takes ALL content
 * from the front-matter fields and renders the canonical four-section body.
 * This keeps the stub format compact and makes idempotency byte-stable
 * (re-running the extractor on the same staging stub produces the same
 * canonical ADR).
 *
 * Optional front-matter keys (forwarded through to the canonical ADR):
 *   - supersedes: <integer ADR number>   # if this decision replaces a prior ADR
 *   - supersededBy: <integer>            # rare on first write; usually filled later
 *
 * If the `story` field disagrees with the staging directory's storyId the
 * stub is rejected (throws); this catches subagent typos before they pollute
 * `docs/decisions/`.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * IDEMPOTENCY (AC-C4)
 * ──────────────────────────────────────────────────────────────────────────
 *
 * - On every call: read all staging files for <storyId>; convert to ADRs; THEN
 *   delete the staging directory. A re-run on the same story finds an empty
 *   staging dir → produces zero new ADR files.
 * - INDEX.md is rebuilt from scratch on every call by walking
 *   `docs/decisions/ADR-*.md`. Same set of ADRs ⇒ byte-identical INDEX rows.
 * - "no new decisions" rows are appended on stories that staged zero stubs
 *   AND did not already have a `| <storyId> | no new decisions | <sha> |`
 *   row. The grep guard makes a re-run on the same no-decisions story leave
 *   the row count at 1.
 */

import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  rmSync,
} from "node:fs";
import { join, resolve } from "node:path";

// ── Constants ────────────────────────────────────────────────────────────

const DECISIONS_DIR = "docs/decisions";
const STAGING_BASE = ".forge/staging/adr";
const ADR_FILE_RE = /^ADR-(\d{4})-(.+)\.md$/;
const INDEX_FILE = "INDEX.md";
const INDEX_HEADER = [
  "# Architecture Decision Records",
  "",
  "<!-- agent-first: this file is auto-regenerated by adr-extractor on every story PASS. Do not hand-edit; edits are overwritten. -->",
  "",
  "| ADR | Story | Title | Date | Status |",
  "| --- | --- | --- | --- | --- |",
];
const NO_DECISIONS_HEADER = [
  "",
  "## No-decisions registry",
  "",
  "Stories whose PASS recorded no material architectural decisions. One row per story; deduped on re-run.",
  "",
  "| Story | Note | Commit |",
  "| --- | --- | --- |",
];
const VALID_STATUSES = new Set(["Proposed", "Accepted", "Superseded", "Deprecated"]);

// ── Types ────────────────────────────────────────────────────────────────

export interface AdrExtractorInput {
  /** Absolute path to project root (must contain a writeable `docs/decisions/`). */
  projectPath: string;
  /** Story id whose staged stubs should be canonicalised. */
  storyId: string;
  /** Optional 40-char hex git SHA captured at PASS time. `"unknown"` if absent. */
  gitSha?: string;
  /** ISO-8601 calendar date used for new ADRs' `date:` field. Defaults to today. */
  today?: string;
}

export interface AdrExtractorResult {
  /** Absolute paths to ADR files newly created during this call. */
  newAdrPaths: string[];
  /** Whether a "no new decisions" row was appended to INDEX.md this call. */
  appendedNoDecisionsRow: boolean;
  /** Absolute path to the regenerated INDEX.md. */
  indexPath: string;
}

interface StubFrontMatter {
  title: string;
  story: string;
  context: string;
  decision: string;
  consequences: string;
  alternatives: string;
  supersedes?: number | null;
  supersededBy?: number | null;
}

interface ParsedAdr {
  adr: number;
  title: string;
  story: string;
  date: string;
  status: string;
  filePath: string;
}

// ── Front-matter parsing ─────────────────────────────────────────────────

/**
 * Parse a stub's YAML front-matter. Tolerates string scalars (quoted or
 * unquoted), integer scalars, and explicit nulls. Throws on malformed
 * structure (no fence, missing required field, wrong type).
 */
function parseStubFrontMatter(text: string, sourceLabel: string): StubFrontMatter {
  if (!text.startsWith("---\n") && !text.startsWith("---\r\n")) {
    throw new Error(
      `adr-extractor: stub ${sourceLabel} must begin with a \`---\` YAML front-matter fence`,
    );
  }
  const normalised = text.replace(/\r\n/g, "\n");
  const m = normalised.match(/^---\n([\s\S]*?)\n---/);
  if (!m) {
    throw new Error(
      `adr-extractor: stub ${sourceLabel} front-matter fence is not closed with a trailing \`---\``,
    );
  }
  const root: Record<string, string | number | null> = {};
  for (const line of m[1].split("\n")) {
    if (line.trim() === "" || line.trimStart().startsWith("#")) continue;
    const indent = line.length - line.trimStart().length;
    if (indent !== 0) {
      throw new Error(`adr-extractor: stub ${sourceLabel} unexpected indented line: "${line}"`);
    }
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) {
      throw new Error(`adr-extractor: stub ${sourceLabel} line missing ":" — "${line}"`);
    }
    const key = line.slice(0, colonIdx).trim();
    root[key] = parseScalarValue(line.slice(colonIdx + 1).trim());
  }
  const required = ["title", "story", "context", "decision", "consequences", "alternatives"];
  for (const k of required) {
    const v = root[k];
    if (v === undefined || v === null || (typeof v === "string" && v.trim() === "")) {
      throw new Error(
        `adr-extractor: stub ${sourceLabel} missing or empty required field: ${k}`,
      );
    }
    if (typeof v !== "string") {
      throw new Error(
        `adr-extractor: stub ${sourceLabel} field ${k} must be a string (got ${typeof v})`,
      );
    }
  }
  const out: StubFrontMatter = {
    title: root.title as string,
    story: root.story as string,
    context: root.context as string,
    decision: root.decision as string,
    consequences: root.consequences as string,
    alternatives: root.alternatives as string,
  };
  if ("supersedes" in root) {
    const v = root.supersedes;
    if (v !== null && (typeof v !== "number" || !Number.isInteger(v) || v < 1)) {
      throw new Error(
        `adr-extractor: stub ${sourceLabel} supersedes must be null or positive integer (got ${JSON.stringify(v)})`,
      );
    }
    out.supersedes = v as number | null;
  }
  if ("supersededBy" in root) {
    const v = root.supersededBy;
    if (v !== null && (typeof v !== "number" || !Number.isInteger(v) || v < 1)) {
      throw new Error(
        `adr-extractor: stub ${sourceLabel} supersededBy must be null or positive integer (got ${JSON.stringify(v)})`,
      );
    }
    out.supersededBy = v as number | null;
  }
  return out;
}

function parseScalarValue(raw: string): string | number | null {
  if (raw === "" || raw === "null" || raw === "~") return null;
  if ((raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"))) {
    return raw.slice(1, -1);
  }
  if (/^-?\d+$/.test(raw)) return parseInt(raw, 10);
  return raw;
}

/**
 * Parse a canonicalised ADR file's front-matter (used by INDEX rebuilder).
 * Looser than the stub parser — tolerates and ignores unknown fields so older
 * schema-revision ADRs still index.
 */
function parseAdrFrontMatter(text: string, sourceLabel: string): ParsedAdr {
  const normalised = text.replace(/\r\n/g, "\n");
  if (!normalised.startsWith("---\n")) {
    throw new Error(`adr-extractor: ${sourceLabel} missing front-matter fence`);
  }
  const m = normalised.match(/^---\n([\s\S]*?)\n---/);
  if (!m) {
    throw new Error(`adr-extractor: ${sourceLabel} front-matter fence not closed`);
  }
  const fm: Record<string, string | number | null> = {};
  for (const line of m[1].split("\n")) {
    if (line.trim() === "" || line.trimStart().startsWith("#")) continue;
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    fm[key] = parseScalarValue(line.slice(colonIdx + 1).trim());
  }
  const title = typeof fm.title === "string" ? fm.title : "";
  const story = typeof fm.story === "string" ? fm.story : "";
  const date = typeof fm.date === "string" ? fm.date : "";
  const status = typeof fm.status === "string" ? fm.status : "";
  const adrNum = typeof fm.adr === "number" ? fm.adr : NaN;
  if (!Number.isInteger(adrNum)) {
    throw new Error(`adr-extractor: ${sourceLabel} adr field is not an integer`);
  }
  if (!VALID_STATUSES.has(status)) {
    throw new Error(`adr-extractor: ${sourceLabel} unknown status: "${status}"`);
  }
  return { adr: adrNum, title, story, date, status, filePath: sourceLabel };
}

// ── Numbering ────────────────────────────────────────────────────────────

/**
 * Scan `docs/decisions/` and return the next ADR number (max + 1, starting
 * at 1 if no ADRs exist). Stable across re-runs because it walks the live
 * filesystem.
 */
function nextAdrNumber(decisionsDir: string): number {
  if (!existsSync(decisionsDir)) return 1;
  let max = 0;
  for (const name of readdirSync(decisionsDir)) {
    const m = name.match(ADR_FILE_RE);
    if (!m) continue;
    const n = parseInt(m[1], 10);
    if (Number.isFinite(n) && n > max) max = n;
  }
  return max + 1;
}

function pad4(n: number): string {
  return String(n).padStart(4, "0");
}

/**
 * Slug a title into a filename-safe segment. Lowercase, strip non-alphanum,
 * collapse whitespace + underscores to single dashes, trim, cap at 60 chars.
 */
function slugify(title: string): string {
  const s = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return s || "decision";
}

// ── Canonical ADR rendering ──────────────────────────────────────────────

function renderAdrFile(args: {
  adr: number;
  storyId: string;
  date: string;
  fm: StubFrontMatter;
}): string {
  const { adr, storyId, date, fm } = args;
  const fmLines = [
    "---",
    `adr: ${adr}`,
    `status: "Accepted"`,
    `story: "${storyId}"`,
    `date: "${date}"`,
    `title: ${quoteString(fm.title)}`,
  ];
  if (fm.supersedes !== undefined) {
    fmLines.push(`supersedes: ${fm.supersedes === null ? "null" : fm.supersedes}`);
  }
  if (fm.supersededBy !== undefined) {
    fmLines.push(`supersededBy: ${fm.supersededBy === null ? "null" : fm.supersededBy}`);
  }
  fmLines.push("---", "");
  const body = [
    `# ADR-${pad4(adr)}: ${fm.title}`,
    "",
    "## Context",
    "",
    fm.context.trim(),
    "",
    "## Decision",
    "",
    fm.decision.trim(),
    "",
    "## Consequences",
    "",
    fm.consequences.trim(),
    "",
    "## Alternatives considered",
    "",
    fm.alternatives.trim(),
    "",
  ];
  return fmLines.concat(body).join("\n");
}

function quoteString(s: string): string {
  // Always emit double-quoted strings. Escape embedded double-quotes.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// ── INDEX.md rebuild ─────────────────────────────────────────────────────

interface ExistingIndex {
  noDecisionsRows: string[]; // raw lines like "| US-01 | no new decisions | abc... |"
}

/**
 * Read the existing INDEX.md (if any) to recover the no-decisions rows. The
 * ADR rows are NOT recovered — they are regenerated from filesystem on every
 * call so the rebuild is byte-stable.
 */
function readExistingIndex(indexPath: string): ExistingIndex {
  const out: ExistingIndex = { noDecisionsRows: [] };
  if (!existsSync(indexPath)) return out;
  const text = readFileSync(indexPath, "utf-8").replace(/\r\n/g, "\n");
  for (const line of text.split("\n")) {
    if (/^\|\s+\S+\s+\|\s+no new decisions\s+\|/.test(line)) {
      out.noDecisionsRows.push(line);
    }
  }
  return out;
}

function buildIndex(
  decisionsDir: string,
  preservedNoDecisionsRows: string[],
): string {
  const adrs: ParsedAdr[] = [];
  if (existsSync(decisionsDir)) {
    for (const name of readdirSync(decisionsDir)) {
      if (!ADR_FILE_RE.test(name)) continue;
      const filePath = join(decisionsDir, name);
      const text = readFileSync(filePath, "utf-8");
      try {
        adrs.push(parseAdrFrontMatter(text, name));
      } catch (err) {
        // Defensive: a malformed ADR shouldn't break the rebuild for everything
        // else. Log and skip — operator can fix in-place.
        console.error(
          `adr-extractor: skipping ${name} during INDEX rebuild: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }
  }
  // Sort by ADR number for stable output.
  adrs.sort((a, b) => a.adr - b.adr);

  const lines = [...INDEX_HEADER];
  for (const a of adrs) {
    lines.push(
      `| ADR-${pad4(a.adr)} | ${a.story} | ${a.title} | ${a.date} | ${a.status} |`,
    );
  }
  // No-decisions registry (preserved across rebuilds; deduped on append).
  if (preservedNoDecisionsRows.length > 0) {
    lines.push(...NO_DECISIONS_HEADER);
    // Sort no-decisions rows for stable output (by storyId, the first cell).
    const sorted = [...preservedNoDecisionsRows].sort();
    lines.push(...sorted);
  }
  lines.push("");
  return lines.join("\n");
}

// ── Main entry ───────────────────────────────────────────────────────────

/**
 * Process all staged ADR stubs for `storyId`, canonicalise them into
 * `docs/decisions/`, delete the staging dir, and rebuild `INDEX.md`.
 *
 * Idempotency contract (AC-C4):
 *   - Re-running with no new staging stubs is a no-op for ADR files; INDEX
 *     rebuild is byte-stable (same input set ⇒ same output).
 *   - Stories with zero stubs append exactly one
 *     `| <storyId> | no new decisions | <sha> |` row to INDEX.md, deduped on
 *     re-run.
 *
 * Returns metadata for the caller to stamp into `RunRecord.generatedDocs.adrPaths`.
 */
export function processStory(input: AdrExtractorInput): AdrExtractorResult {
  const projectPath = resolve(input.projectPath);
  const storyId = input.storyId;
  const today = input.today ?? new Date().toISOString().slice(0, 10);
  const gitSha = input.gitSha && /^[0-9a-f]{40}$/.test(input.gitSha)
    ? input.gitSha
    : "unknown";

  const decisionsDir = join(projectPath, DECISIONS_DIR);
  mkdirSync(decisionsDir, { recursive: true });

  const stagingDir = join(projectPath, STAGING_BASE, storyId);
  const stagingStubs: Array<{ filename: string; fm: StubFrontMatter; raw: string }> = [];

  if (existsSync(stagingDir)) {
    const stagingNames = readdirSync(stagingDir)
      .filter((n) => n.endsWith(".md"))
      .sort(); // alphabetical for monotonic-by-tie ordering
    for (const name of stagingNames) {
      const stubPath = join(stagingDir, name);
      const raw = readFileSync(stubPath, "utf-8");
      // Will throw on malformed; caller (evaluate.ts) catches and logs.
      const fm = parseStubFrontMatter(raw, `${storyId}/${name}`);
      // Sanity: stub's front-matter `story` must agree with the dir name.
      if (fm.story !== storyId) {
        throw new Error(
          `adr-extractor: stub ${storyId}/${name} declares story="${fm.story}" but is staged under storyId "${storyId}"`,
        );
      }
      stagingStubs.push({ filename: name, fm, raw });
    }
  }

  const newAdrPaths: string[] = [];
  if (stagingStubs.length > 0) {
    let nextNum = nextAdrNumber(decisionsDir);
    for (const stub of stagingStubs) {
      const adr = nextNum++;
      const slug = slugify(stub.fm.title);
      const filename = `ADR-${pad4(adr)}-${slug}-${storyId}.md`;
      const outPath = join(decisionsDir, filename);
      const rendered = renderAdrFile({ adr, storyId, date: today, fm: stub.fm });
      writeFileSync(outPath, rendered, "utf-8");
      newAdrPaths.push(outPath);
    }
    // Delete staging files + the per-story dir. Leaves the parent
    // `.forge/staging/adr/` in place for other concurrent stories.
    rmSync(stagingDir, { recursive: true, force: true });
  } else if (existsSync(stagingDir)) {
    // Empty staging dir — clean it up.
    rmSync(stagingDir, { recursive: true, force: true });
  }

  // Rebuild INDEX.md from scratch.
  const indexPath = join(decisionsDir, INDEX_FILE);
  const existing = readExistingIndex(indexPath);
  const preserved = [...existing.noDecisionsRows];
  let appendedNoDecisionsRow = false;
  if (stagingStubs.length === 0 && newAdrPaths.length === 0) {
    // No new ADRs for this story this call. AC-C1 says PASS leaves either
    // an ADR file for this story OR a no-decisions row — so first check
    // whether the story ALREADY has an ADR on disk; only append the
    // no-decisions row if it doesn't.
    const storyHasExistingAdr = storyHasAnyAdr(decisionsDir, storyId);
    if (!storyHasExistingAdr) {
      const rowRe = new RegExp(
        `^\\|\\s+${escapeRegex(storyId)}\\s+\\|\\s+no new decisions\\s+\\|`,
      );
      const already = preserved.some((line) => rowRe.test(line));
      if (!already) {
        preserved.push(`| ${storyId} | no new decisions | ${gitSha} |`);
        appendedNoDecisionsRow = true;
      }
    }
  }
  const indexBody = buildIndex(decisionsDir, preserved);
  writeFileSync(indexPath, indexBody, "utf-8");

  return {
    newAdrPaths,
    appendedNoDecisionsRow,
    indexPath,
  };
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Does any ADR file in `decisionsDir` belong to `storyId`? Two-stage check:
 * (1) filename suffix `-<storyId>.md` is a fast path; (2) parsing the front-
 * matter `story:` field is the authoritative check (catches manual moves).
 */
function storyHasAnyAdr(decisionsDir: string, storyId: string): boolean {
  if (!existsSync(decisionsDir)) return false;
  const suffix = `-${storyId}.md`;
  for (const name of readdirSync(decisionsDir)) {
    if (!ADR_FILE_RE.test(name)) continue;
    if (name.endsWith(suffix)) return true; // fast path
    try {
      const text = readFileSync(join(decisionsDir, name), "utf-8");
      const parsed = parseAdrFrontMatter(text, name);
      if (parsed.story === storyId) return true;
    } catch {
      // skip malformed
    }
  }
  return false;
}
