/**
 * idempotent-write.ts — small helper that skips `writeFileSync` when the
 * generated content would be byte-identical to (or equivalent to, ignoring
 * volatile timestamp/date stamps) the existing on-disk content.
 *
 * Why this exists (W3 / forge-harness #514): every story PASS regenerates
 * `docs/decisions/INDEX.md` and `docs/generated/TECHNICAL-SPEC.md`. The
 * generators stamp `today` into a visible "> Generated by forge-harness on
 * YYYY-MM-DD." line and refresh `lastUpdated:` ISO timestamps in the
 * front-matter. When ALL OTHER content is unchanged, the file should not
 * change either — otherwise consumer repos pick up a 1-line dated-banner diff
 * on every PASS.
 *
 * Strategy (option (b) per the W3 plan): read existing on-disk content,
 * normalize both the existing and proposed bytes by stripping volatile
 * sections (the visible date line and `lastUpdated:` timestamps), and skip
 * the write if the normalized content matches. The on-disk file keeps its
 * prior timestamps, so subsequent reads stay byte-stable across runs.
 *
 * Preserves intentional drift: when the BODY changes (new ADR row, new story
 * section, edited bullet), the normalized comparison differs and the write
 * proceeds — the date and `lastUpdated:` then refresh together as a single
 * coherent stamp on a real change.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";

/**
 * Strip the visible "Generated by forge-harness on YYYY-MM-DD." blockquote
 * line and any `lastUpdated: "<ISO>"` lines from `text`. The result is the
 * "stable shape" of the doc — body content, schema version, story IDs,
 * lastGitSha, comment-block header, table rows. Two files with the same
 * stable shape but different volatile stamps SHOULD be considered identical.
 */
function stripVolatile(text: string): string {
  return text
    .replace(/^> Generated by forge-harness on \d{4}-\d{2}-\d{2}\.$/gm, "> Generated by forge-harness on <DATE>.")
    .replace(/lastUpdated:\s*"[^"]*"/g, 'lastUpdated: "<TS>"');
}

/**
 * Write `content` to `path` only if the existing on-disk content would
 * differ in a meaningful way (after volatile-stamp normalization).
 *
 * Returns true if a write happened, false if the call was a no-op because
 * the existing file already represents the same logical state.
 *
 * No-op behavior preserves the existing file's timestamps verbatim — the
 * caller does NOT need to feed `existing` content back in; we just don't
 * touch the file.
 */
export function idempotentWrite(path: string, content: string): boolean {
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf-8");
    if (stripVolatile(existing) === stripVolatile(content)) {
      return false;
    }
  }
  writeFileSync(path, content, "utf-8");
  return true;
}

/**
 * Test-only export of the volatile-stripping function. Lets the unit-test
 * suite assert exactly which substrings are considered volatile without
 * having to write-and-read a real file.
 */
export const __test = { stripVolatile };
