/**
 * spec-generator.ts — synchronous post-PASS author of
 * `docs/generated/TECHNICAL-SPEC.md`.
 *
 * v0.36.0 Phase B (improvement #2). Called from `server/tools/evaluate.ts`
 * IMMEDIATELY BEFORE `writeRunRecord` on a story-mode PASS — the call is
 * sequenced this way so `RunRecord.generatedDocs` can carry the result of
 * this function rather than needing a second write. Synchronous by mandate
 * (plan §122 / AC-B1): the spec MUST exist by the time `forge_evaluate`
 * returns to the caller; async would require an unspecified poll window and
 * break the contract that "PASS means docs are current."
 *
 * Cost: one `trackedCallClaude` round-trip per PASS (~$0.03–$0.10 for the
 * sizes we see). Plan AC-B6 caps total at $0.80 / 13-story phase.
 *
 * Idempotency contract (AC-B2): re-running the spec generator on the same
 * story leaves the body section count at exactly one and updates only the
 * matching `stories[i].lastUpdated` entry in the top-of-file front-matter.
 * The merge is by `id`, not by position.
 */

import Anthropic from "@anthropic-ai/sdk";
import { readFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { userInfo } from "node:os";
import { dirname, resolve } from "node:path";
import { idempotentWrite } from "./idempotent-write.js";
import type { EvalReport } from "../types/eval-report.js";
import { KEYCHAIN_SERVICE_NAME } from "./anthropic.js";
import { RunContext, trackedCallClaude } from "./run-context.js";
import {
  buildSourceVocabulary,
  chainResolves,
  renderVocabularyForPrompt,
  vocabularyContains,
  type SourceVocabulary,
} from "./spec-source-vocabulary.js";
import type { SpecGeneratorWarning } from "./run-record.js";

// ── Constants ────────────────────────────────────────────────────────────

const SCHEMA_VERSION = "1.0.0" as const;
const REQUIRED_SECTIONS = ["api-contracts", "data-models", "invariants", "test-surface"] as const;
type SectionName = (typeof REQUIRED_SECTIONS)[number];

const SPEC_REL_PATH = "docs/generated/TECHNICAL-SPEC.md";

/**
 * I6 — byte-stable HTML-comment placeholder body used when the synthesizer
 * (`synth()`) throws (LLM unavailable: 401 after retry, network out, no
 * Claude Code session, etc). MUST contain no timestamps, no random ids, and
 * no per-run state — `idempotentWrite` short-circuits the second consecutive
 * no-creds run as a no-op only when each section body is byte-identical.
 * The leading `<!--` keeps the placeholder agent-first-friendly: rendered
 * Markdown shows nothing, but a consumer reading the source sees the cause
 * inline next to the section heading.
 */
const SHELL_ONLY_PLACEHOLDER_BODY =
  "<!-- forge: placeholder body — LLM unavailable; see warnings -->";

/** Truncation cap for the `spec-gen-shell-only` warning message — mirrors F4. */
const SHELL_ONLY_MESSAGE_MAX = 200;

/**
 * v0.42.0 (AC-4/AC-5) — default cap (in seconds) for the retry-on-429 sleep
 * when `FORGE_SPEC_RETRY_ON_429` is not set. Conservative: 60 seconds leaves
 * headroom under common operator-configured MCP tool-call timeouts (typically
 * 30-120s). Operators with tighter limits override via env. Setting
 * `FORGE_SPEC_RETRY_ON_429=0` disables retry entirely. Plan §AC-4.
 */
const RETRY_ON_429_DEFAULT_SEC = 60;

/**
 * v0.42.0 (AC-3) — sleep helper backing the retry-on-429 wrapper. Exported
 * via the `sleepFn` P64 injection seam on `SpecGeneratorInput` so vitest can
 * stub without burning real wall-clock. Default = `setTimeout`-backed promise.
 */
function defaultSleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * v0.42.0 (AC-4) — parse the `FORGE_SPEC_RETRY_ON_429` env var. Returns the
 * configured cap in SECONDS, or the default (60) when unset / malformed.
 * `0` is a legitimate "retry disabled" value and propagates through.
 * Negative or non-numeric values fall back to the default per F46
 * (no-silent-numeric-default — we warn-and-default rather than crash because
 * the spec-generator is on the PASS hot path; an env var typo must not nuke
 * a story's verdict, just disable the retry behaviour and log the misuse).
 */
function parseRetryOn429Cap(raw: string | undefined): number {
  if (raw === undefined || raw === "") return RETRY_ON_429_DEFAULT_SEC;
  const trimmed = raw.trim();
  if (!/^\d+$/.test(trimmed)) {
    console.error(
      `spec-generator: ignoring malformed FORGE_SPEC_RETRY_ON_429="${raw}" (expected non-negative integer seconds); using default ${RETRY_ON_429_DEFAULT_SEC}s`,
    );
    return RETRY_ON_429_DEFAULT_SEC;
  }
  return Number.parseInt(trimmed, 10);
}

/**
 * Agent-first header (Bundle 1a). Five HTML-comment lines + 1 blank line are
 * BYTE-IDENTICAL across regenerations (idempotency contract AC-1a-3). The
 * visible "Generated by ..." date line that follows refreshes on every call
 * and is excluded from idempotency checks. Together they satisfy AC-1a-2.
 */
const AGENT_FIRST_COMMENT_BLOCK = [
  "<!-- agent-first: this file is auto-regenerated by forge-harness on every story PASS. -->",
  "<!-- Source of truth: docs/decisions/<US-NN>/*.md (ADRs) and docs/generated/<US-NN>.md (TECHNICAL-SPEC). -->",
  "<!-- Do not hand-edit; edits are overwritten on next regeneration. -->",
  "<!-- Regeneration tool: forge-harness `forge_evaluate` (PASS verdict path). -->",
  "<!-- Design rationale: P60 Build for Consumer, Not Author. -->",
];

/**
 * Match the leading agent-first header (5 HTML comments + blank line + visible
 * "Generated by ..." line + blank line). Used by `parseSpec` to skip the header
 * before locating the YAML front-matter fence.
 */
const AGENT_FIRST_HEADER_RE =
  /^(?:<!--[^\n]*-->\n){5}\n> Generated by forge-harness on \d{4}-\d{2}-\d{2}\.\n\n/;

// ── Types ────────────────────────────────────────────────────────────────

export interface SpecGeneratorInput {
  /** Absolute path to project root (must contain a writeable `docs/generated/`). */
  projectPath: string;
  /** Story id this section is being authored for (must match `## story: <id>`). */
  storyId: string;
  /** The PASS-verdict eval report, used as primary structured evidence. */
  evalReport: EvalReport;
  /**
   * Story's affectedPaths (directory prefixes or file paths, relative to
   * `projectPath`). Drives the source-vocabulary extractor. Empty / omitted
   * paths produce a "No source vocabulary available" prompt and instruct the
   * LLM to emit `(none)` for api-contracts and data-models.
   */
  affectedPaths?: string[];
  /** Optional 40-char hex git SHA captured at PASS time. `"unknown"` if absent. */
  gitSha?: string;
  /** RunContext for cost/audit tracking; spec-generator participates in the run's $$$ totals. */
  ctx: RunContext;
  /** Override LLM with a deterministic injected synthesizer (for tests). */
  synthesize?: (req: SynthesisRequest) => Promise<SynthesisResponse>;
  /**
   * #546 / v0.41.1 — override the macOS Keychain probe's `execFileSync`
   * for deterministic regression-positive tests. P64 producer/consumer
   * seam: lets AC-546-2 unit tests assert `keychainOnly` presence/absence
   * directly instead of inferring from code-reading. Mirrors the
   * `synthesize` injection-seam pattern above. Default = real
   * `execFileSync` from `node:child_process` — production behavior unchanged.
   */
  execFileSyncFn?: typeof execFileSync;
  /**
   * v0.42.0 (AC-3 / P64) — override the retry-on-429 sleep so vitest can
   * exercise the retry path without burning real wall-clock. Default =
   * `defaultSleep` (a `setTimeout`-backed promise). Tests inject a no-op
   * recorder to assert sleep duration was clamped to the configured cap.
   */
  sleepFn?: (ms: number) => Promise<void>;
}

export interface SpecGeneratorResult {
  specPath: string;
  genTimestamp: string;
  genTokens: { inputTokens: number; outputTokens: number };
  contracts: string[];
  bodyChanged: boolean;
  /**
   * Strip events from the post-validator. Empty array if no bullets were
   * stripped (or if validator mode is "warn"). The caller stamps this onto
   * `RunRecord.generatedDocs.warnings` (AC-10).
   */
  warnings: SpecGeneratorWarning[];
}

export interface SynthesisRequest {
  storyId: string;
  evalReport: EvalReport;
  diffSummary: string;
  /**
   * Pre-rendered "Real symbols available" Markdown block for the user
   * prompt. Either a real vocabulary listing or the "No source vocabulary
   * available" fallback. The default synthesizer's `buildUserPrompt`
   * inserts this verbatim before the AC list.
   */
  vocabularyPrompt: string;
}

export interface SynthesisResponse {
  /** Tool ids touched by this story (e.g. ["forge_evaluate", "forge_generate"]). */
  contracts: string[];
  /** Pre-rendered Markdown for each of the four required subsections. */
  sections: Record<SectionName, string>;
  /** Token usage from the LLM call (zero for synthesised/test paths). */
  tokens: { inputTokens: number; outputTokens: number };
}

// ── Front-matter helpers (mirrors validate-tech-spec.mjs grammar) ────────

interface ParsedSpec {
  frontMatter: {
    schemaVersion: string;
    lastUpdated: string;
    stories: Array<{ id: string; lastUpdated: string; lastGitSha: string }>;
  };
  body: string;
}

function parseSpec(text: string): ParsedSpec {
  const normalised = text.replace(/\r\n/g, "\n");
  // Skip the agent-first header (Bundle 1a) if present. The header lives BEFORE
  // the YAML front-matter fence; older spec files written prior to v0.40.0
  // start directly with `---\n` and pass through unchanged.
  const stripped = normalised.replace(AGENT_FIRST_HEADER_RE, "");
  const m = stripped.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error("spec file missing closed `---` front-matter fence");
  const fm = parseFrontMatterYaml(m[1]);
  return { frontMatter: fm, body: m[2] };
}

function parseFrontMatterYaml(yaml: string): ParsedSpec["frontMatter"] {
  const lines = yaml.split("\n");
  const out: Partial<ParsedSpec["frontMatter"]> = {};
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.trim() === "" || line.trimStart().startsWith("#")) { i++; continue; }
    const colon = line.indexOf(":");
    if (colon === -1) throw new Error(`malformed front-matter line: "${line}"`);
    const key = line.slice(0, colon).trim();
    const valueRaw = line.slice(colon + 1).trim();
    if (key === "stories") {
      const items: ParsedSpec["frontMatter"]["stories"] = [];
      if (valueRaw === "[]") { out.stories = []; i++; continue; }
      i++;
      while (i < lines.length) {
        const ln = lines[i];
        if (ln.trim() === "") { i++; continue; }
        const indent = ln.length - ln.trimStart().length;
        if (indent === 0) break;
        const itemMatch = ln.match(/^(\s+)-\s+(.+)$/);
        if (!itemMatch) throw new Error(`expected list item, got "${ln}"`);
        const itemIndent = itemMatch[1].length;
        const fieldIndent = itemIndent + 2;
        const item: Record<string, string> = {};
        Object.assign(item, parseScalar(itemMatch[2]));
        i++;
        while (i < lines.length) {
          const fl = lines[i];
          if (fl.trim() === "") { i++; continue; }
          const fIndent = fl.length - fl.trimStart().length;
          if (fIndent < fieldIndent) break;
          if (fl.trimStart().startsWith("- ")) break;
          Object.assign(item, parseScalar(fl.trimStart()));
          i++;
        }
        items.push(item as ParsedSpec["frontMatter"]["stories"][number]);
      }
      out.stories = items;
      continue;
    }
    (out as Record<string, unknown>)[key] = unquote(valueRaw);
    i++;
  }
  if (!out.schemaVersion) throw new Error("front-matter missing schemaVersion");
  if (!out.lastUpdated) throw new Error("front-matter missing lastUpdated");
  if (!out.stories) out.stories = [];
  return out as ParsedSpec["frontMatter"];
}

function parseScalar(text: string): Record<string, string> {
  const colon = text.indexOf(":");
  if (colon === -1) throw new Error(`scalar missing colon: "${text}"`);
  const k = text.slice(0, colon).trim();
  const v = unquote(text.slice(colon + 1).trim());
  return { [k]: v };
}

function unquote(raw: string): string {
  if (raw === "") return "";
  if ((raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"))) {
    return raw.slice(1, -1);
  }
  return raw;
}

function renderFrontMatter(fm: ParsedSpec["frontMatter"]): string {
  const lines = [
    `schemaVersion: "${fm.schemaVersion}"`,
    `lastUpdated: "${fm.lastUpdated}"`,
    fm.stories.length === 0 ? "stories: []" : "stories:",
  ];
  for (const s of fm.stories) {
    lines.push(`  - id: "${s.id}"`);
    lines.push(`    lastUpdated: "${s.lastUpdated}"`);
    lines.push(`    lastGitSha: "${s.lastGitSha}"`);
  }
  return lines.join("\n");
}

// ── Body section helpers ─────────────────────────────────────────────────

interface BodySection { id: string; markdown: string }

function splitBodyByStory(body: string): BodySection[] {
  const lines = body.split("\n");
  const sections: BodySection[] = [];
  let curId: string | null = null;
  let buf: string[] = [];
  const flush = () => {
    if (curId !== null) {
      // W4 (#515): trim trailing whitespace so a section's extracted markdown
      // is uniform regardless of whether trailing blank lines belong to it
      // or to the next section. Cross-section non-mutation depends on this:
      // section bytes must NOT vary with neighboring-section position.
      sections.push({ id: curId, markdown: buf.join("\n").replace(/\s+$/, "") });
    }
    curId = null; buf = [];
  };
  for (const line of lines) {
    const m = line.match(/^## story: (\S.*)$/);
    if (m) {
      flush();
      curId = m[1].trim();
      buf = [line];
      continue;
    }
    if (line.startsWith("## ") && curId !== null) {
      flush();
      // non-story `##` heading — preserve as a free-floating section
      sections.push({ id: `__free_${sections.length}__`, markdown: line });
      continue;
    }
    if (curId !== null) buf.push(line);
  }
  flush();
  return sections;
}

function renderStorySection(storyId: string, sections: Record<SectionName, string>): string {
  const parts: string[] = [`## story: ${storyId}`, ""];
  for (const name of REQUIRED_SECTIONS) {
    parts.push(`### ${name}`, "", sections[name].trim() === "" ? "(none)" : sections[name].trim(), "");
  }
  return parts.join("\n");
}

// ── Diff capture ─────────────────────────────────────────────────────────

/**
 * Best-effort: capture a short diff summary for prompt context. Failure is
 * swallowed (returns empty string) — the spec-generator must still produce
 * a section even when git is unavailable.
 */
function captureDiffSummary(cwd: string): string {
  try {
    const stat = execFileSync("git", ["diff", "--stat", "HEAD~1...HEAD"], {
      cwd,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return stat.length > 4000 ? stat.slice(0, 4000) + "\n…(truncated)" : stat;
  } catch {
    return "";
  }
}

// ── LLM synthesis ────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are the spec-generator for forge-harness's living TECHNICAL-SPEC.md.

For one story (a unit of shipped work), you write four short structured Markdown subsections capturing what the diff settled.

Output ONLY a single JSON object. Schema:

{
  "contracts": ["<mcp-tool-id>", ...],   // MCP tool ids touched (e.g. "forge_evaluate"). Empty array if none.
  "sections": {
    "api-contracts":  "<markdown>",       // bullet list, one bullet per public surface change
    "data-models":    "<markdown>",       // bullet list, one bullet per persisted/wire-format shape change
    "invariants":     "<markdown>",       // bullet list of properties that MUST hold post-merge
    "test-surface":   "<markdown>"        // bullet list of test files / coverage ratchets added or changed
  }
}

Rules:
- Agent-first. NO prose narrative, NO motivation, NO storytelling.
- Each subsection is a Markdown bullet list. Use \`-\` bullets, one fact per bullet.
- Bullets in "api-contracts" MUST start with a backtick-wrapped identifier (e.g. "- \`forge_evaluate.generatedDocs\`: ...").
- If a subsection genuinely has nothing to record, return the literal string "(none)".
- Be terse. Each bullet should be one line, ideally under 120 chars.
- The "contracts" array is the canonical list of MCP tool identifiers (top-level tool names only, no method paths) that the diff TOUCHES, regardless of whether each tool has a dedicated bullet under api-contracts.
- Do NOT invent contracts. If you can't see a tool change in the evidence, do not list it.
- Every backtick-quoted identifier you emit MUST appear in the "Real symbols available" section of the user prompt. If a needed symbol isn't there, emit "(none)" for that section.
- Attribution discipline (W5): when an "invariants" or "api-contracts" bullet asserts that some symbol "MUST" do something, attribute it to the layer that ACTUALLY implements the behaviour — the constant, function, or method whose body contains the logic. Do NOT bind invariants to upstream callers, just-forwarders, or proxy layers that merely route to the implementing layer. If the behaviour is encoded in a constant (e.g. a not-found message string), name the constant; do not name the function that returns it.
- Call-chain grounding (W5): when emitting a dotted identifier like \`Foo.bar()\`, the chain MUST resolve in the source vocabulary — i.e. \`Foo\` must list \`bar\` among its public methods or fields. If the chain doesn't resolve, choose a different identifier or emit "(none)".`;

export function buildUserPrompt(req: SynthesisRequest): string {
  const acLines = req.evalReport.criteria
    .map((c) => `- ${c.id} [${c.status}]: ${c.evidence.slice(0, 200)}`)
    .join("\n");
  return [
    `## Story\n${req.storyId}\n`,
    `## Eval verdict\n${req.evalReport.verdict}\n`,
    `${req.vocabularyPrompt}\n`,
    `## Acceptance criteria results\n${acLines || "(none)"}\n`,
    `## Diff summary\n${req.diffSummary || "(unavailable)"}\n`,
    "Emit the JSON object now.",
  ].join("\n");
}

async function defaultSynthesize(
  ctx: RunContext,
  req: SynthesisRequest,
): Promise<SynthesisResponse> {
  const result = await trackedCallClaude(ctx, "spec-gen", "spec-generator", {
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: buildUserPrompt(req) }],
    jsonMode: true,
  });
  const parsed = (result.parsed ?? {}) as Partial<SynthesisResponse>;
  const sectionsRaw = parsed.sections ?? {};
  const sections: Record<SectionName, string> = {
    "api-contracts": "(none)",
    "data-models": "(none)",
    invariants: "(none)",
    "test-surface": "(none)",
  };
  for (const k of REQUIRED_SECTIONS) {
    const v = (sectionsRaw as Record<string, unknown>)[k];
    if (typeof v === "string" && v.trim() !== "") sections[k] = v;
  }
  const contracts = Array.isArray(parsed.contracts)
    ? parsed.contracts.filter((c): c is string => typeof c === "string")
    : [];
  return {
    contracts,
    sections,
    tokens: {
      inputTokens: result.usage.inputTokens,
      outputTokens: result.usage.outputTokens,
    },
  };
}

// ── Post-validator (Strategy 2: strip unknown identifiers) ────────────────

/**
 * Allowlist of built-in TypeScript / JavaScript globals + standard library
 * symbols. These names are legitimate environment references (return types,
 * generic constraints, exception types) and MUST NOT be stripped even when
 * the project source vocabulary doesn't contain them. Keep terse — when in
 * doubt, omit; the validator is permissive about test-name strings and
 * forge_* tool ids elsewhere.
 */
const TS_BUILTINS = new Set<string>([
  // Promise & async surface
  "Promise", "PromiseLike", "Awaited", "AsyncIterable", "AsyncIterator", "AsyncGenerator",
  // Collections + iteration
  "Array", "ReadonlyArray", "Map", "ReadonlyMap", "Set", "ReadonlySet", "WeakMap", "WeakSet",
  "Iterable", "Iterator", "Generator", "ArrayLike", "Record", "Tuple",
  // Primitives + boxed
  "String", "Number", "Boolean", "Symbol", "BigInt", "Object", "Function",
  // Errors
  "Error", "TypeError", "RangeError", "SyntaxError", "ReferenceError", "URIError", "EvalError", "AggregateError",
  // Utility types
  "Partial", "Required", "Readonly", "Pick", "Omit", "Exclude", "Extract", "NonNullable",
  "Parameters", "ReturnType", "InstanceType", "ThisType", "Uppercase", "Lowercase", "Capitalize", "Uncapitalize",
  // Date/regex/JSON/Math
  "Date", "RegExp", "JSON", "Math",
  // Buffers + binary
  "Buffer", "ArrayBuffer", "SharedArrayBuffer", "DataView",
  "Int8Array", "Uint8Array", "Uint8ClampedArray", "Int16Array", "Uint16Array",
  "Int32Array", "Uint32Array", "Float32Array", "Float64Array", "BigInt64Array", "BigUint64Array",
  // DOM-ish (might appear in mixed code)
  "URL", "URLSearchParams", "Blob", "File", "FormData",
  // Misc
  "Proxy", "Reflect", "WeakRef", "FinalizationRegistry",
]);

/**
 * Mode is `strip` by default. Set `FORGE_SPEC_VALIDATOR_MODE=warn` to keep
 * bullets in the file but still record `warnings` (AC-11). Any other value
 * (or unset) means "strip".
 */
function validatorMode(): "strip" | "warn" {
  const v = process.env.FORGE_SPEC_VALIDATOR_MODE;
  return v === "warn" ? "warn" : "strip";
}

/**
 * Walk every backtick-quoted identifier in each section's bullets. For each
 * identifier not present in `vocab`, either:
 *   - mode=strip: drop the entire bullet line (and emit a warning)
 *   - mode=warn:  leave the bullet (still emit a warning)
 *
 * If a section ends up empty after strips, it is replaced with "(none)".
 *
 * Identifier extraction: any token inside a backtick pair on a bullet line.
 * Bullets are lines that start with `-` (after optional leading whitespace).
 * Identifiers may take the forms `Foo`, `Foo.bar`, `Foo.bar.baz` (only the
 * first two segments are checked — deeper navigation is treated as
 * recognised so long as the prefix matches).
 */
export function validateAgainstVocabulary(
  sections: Record<SectionName, string>,
  vocab: SourceVocabulary,
  storyContext: { filesScanned: number },
): {
  sections: Record<SectionName, string>;
  warnings: Array<
    Extract<
      SpecGeneratorWarning,
      { kind: "stripped-unknown-identifier" } | { kind: "stripped-unknown-chain" }
    >
  >;
} {
  const mode = validatorMode();
  const out: Record<SectionName, string> = { ...sections };
  const warnings: Array<
    Extract<
      SpecGeneratorWarning,
      { kind: "stripped-unknown-identifier" } | { kind: "stripped-unknown-chain" }
    >
  > = [];

  for (const sectionName of REQUIRED_SECTIONS) {
    const text = sections[sectionName];
    if (!text || text.trim() === "" || text.trim() === "(none)") continue;

    const lines = text.split("\n");
    const keptLines: string[] = [];
    for (const line of lines) {
      const isBullet = /^\s*-\s/.test(line);
      if (!isBullet) { keptLines.push(line); continue; }

      // Extract every backtick-quoted token from this bullet, then for each
      // span pull out programming-symbol-shaped identifiers from inside it.
      // The LLM emits bullets like:
      //   - `KnowledgeService.search(query: string): Promise<KnowledgeResult[]>`
      //   - `KnowledgeDocument`: persisted shape with `id`, `content`
      // so the entire backtick span isn't a clean identifier — we have to
      // harvest each capitalised symbol-ish token from within the span.
      const symbolLike: string[] = [];
      const spanRe = /`([^`]+)`/g;
      let m: RegExpExecArray | null;
      while ((m = spanRe.exec(line)) !== null) {
        const span = m[1];
        // Strip generic angle-bracket arguments (`Foo<Bar>` → `Foo`) and
        // array brackets so they don't fragment the identifier.
        const simplified = span.replace(/<[^>]*>/g, "").replace(/\[\]/g, "");
        const tokenRe = /\b([A-Z][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)*)\b/g;
        let tm: RegExpExecArray | null;
        while ((tm = tokenRe.exec(simplified)) !== null) symbolLike.push(tm[1]);
      }
      // Strings inside test-surface ("test name") are quoted with double quotes,
      // not asterisks, so they survive this pass — they don't begin with a capital
      // unless the LLM happened to write a Title Case test name. We let the
      // test-name match handle that path.
      // Also harvest backtick-wrapped quoted strings as test-name candidates.
      // Pattern: `"some string"` — preserve the inner string for test-name match.
      const quotedTestRe = /`"([^"]+)"`/g;
      let qm: RegExpExecArray | null;
      while ((qm = quotedTestRe.exec(line)) !== null) symbolLike.push(qm[1]);

      let bulletKept = true;
      for (const id of symbolLike) {
        // Allow MCP tool ids by string-prefix convention (forge_evaluate, forge_generate, ...).
        if (/^forge_[a-z_]+$/.test(id) || /^forge_[a-z_]+\.[A-Za-z0-9_$]+$/.test(id)) continue;
        // Allow common TypeScript built-ins / globals — these are environment
        // names the LLM legitimately references in signatures and don't need
        // to live in a project source vocabulary.
        if (TS_BUILTINS.has(id)) continue;
        // Top-level segment of a dotted path: if the head is a builtin, skip.
        const head = id.split(".")[0];
        if (TS_BUILTINS.has(head)) continue;
        // W5 (#516) — call-chain check FIRST for dotted identifiers. When the
        // owner is a known class/type but the second segment isn't one of its
        // public methods/fields, emit `stripped-unknown-chain` (a distinct
        // diagnostic) rather than the older `stripped-unknown-identifier`.
        // This catches monday-bot-style mis-attribution where an invariant
        // is bound to a function chain whose member doesn't implement (or
        // even exist in) the asserted shape. When the chain DOES resolve,
        // pass through to the existing `vocabularyContains` accept path.
        if (id.indexOf(".") !== -1 && !chainResolves(vocab, id)) {
          warnings.push({
            kind: "stripped-unknown-chain",
            chain: id,
            section: sectionName,
            filesScanned: storyContext.filesScanned,
          });
          if (mode === "strip") bulletKept = false;
          continue;
        }
        // Two-segment check: `Foo.bar` validates against full string OR the owner being a known class/type.
        const okFull = vocabularyContains(vocab, id);
        if (okFull) continue;
        // Deeper paths: `Foo.bar.baz` — accept if the two-segment prefix is in vocab.
        if (id.indexOf(".") !== -1) {
          const twoSeg = id.split(".").slice(0, 2).join(".");
          if (vocabularyContains(vocab, twoSeg)) continue;
        }
        // Unknown identifier: log warning and (if strip mode) drop bullet.
        warnings.push({
          kind: "stripped-unknown-identifier",
          identifier: id,
          section: sectionName,
          filesScanned: storyContext.filesScanned,
        });
        if (mode === "strip") bulletKept = false;
      }

      if (bulletKept) keptLines.push(line);
    }

    let rebuilt = keptLines.join("\n").trim();
    if (rebuilt === "" || /^[\s-]+$/.test(rebuilt)) rebuilt = "(none)";
    out[sectionName] = rebuilt;
  }

  return { sections: out, warnings };
}

// ── Main entry ───────────────────────────────────────────────────────────

/**
 * Generate or update a story's section in `docs/generated/TECHNICAL-SPEC.md`.
 * Idempotent across re-runs: same story id always produces exactly one
 * `## story: <id>` heading in the body and exactly one entry in the
 * front-matter `stories[]` array.
 *
 * Returns metadata for the caller to stamp into `RunRecord.generatedDocs`.
 */
export async function generateSpecForStory(
  input: SpecGeneratorInput,
): Promise<SpecGeneratorResult> {
  const specPath = resolve(input.projectPath, SPEC_REL_PATH);
  const now = new Date().toISOString();
  const gitShaSafe = input.gitSha && /^[0-9a-f]{40}$/.test(input.gitSha)
    ? input.gitSha
    : "unknown";

  // Read existing spec (or scaffold an empty one).
  let parsed: ParsedSpec;
  if (existsSync(specPath)) {
    const text = readFileSync(specPath, "utf-8");
    try {
      parsed = parseSpec(text);
    } catch (err) {
      // Corrupted file — start fresh, but log the cause so the operator can
      // recover the prior content from git.
      console.error(
        `spec-generator: existing spec at ${specPath} is malformed (${err instanceof Error ? err.message : String(err)}); rewriting from scratch`,
      );
      parsed = emptySpec(now);
    }
  } else {
    parsed = emptySpec(now);
  }

  // Build source vocabulary from the story's affectedPaths. Empty/omitted
  // paths fall back to the "No source vocabulary available" prompt.
  const vocab = buildSourceVocabulary(
    input.projectPath,
    input.affectedPaths ?? [],
  );
  const vocabularyPrompt = renderVocabularyForPrompt(vocab);

  // Synthesise the new section.
  // I6 — single-locus try/catch around `synth()`. When the LLM call fails
  // (auth/network/parse/zod after I8's retry exhausted), fall back to a
  // byte-stable placeholder body so the rest of `generateSpecForStory`
  // (vocab merge, frontmatter `lastUpdated` refresh, section merge,
  // `idempotentWrite`) still runs and the spec file is partially regenerated.
  // The structural fields refresh deterministically; only the prose body is
  // a placeholder until LLM creds return. Mint locus locked here per F49 —
  // the F4 catch in `evaluate.ts` continues to handle truly-non-recoverable
  // throws (e.g. the placeholder write itself fails); see plan §59.
  const synth = input.synthesize ?? ((req) => defaultSynthesize(input.ctx, req));
  const sleep = input.sleepFn ?? defaultSleep;
  const diffSummary = captureDiffSummary(input.projectPath);
  // v0.42.0 (AC-4) — retry cap is read PER CALL (not module-load) so vitest
  // can mutate `process.env.FORGE_SPEC_RETRY_ON_429` between tests.
  const retryOn429Cap = parseRetryOn429Cap(process.env.FORGE_SPEC_RETRY_ON_429);
  // Initialise to a safe shape so the type-checker can prove definite
  // assignment after the retry loop. The shell-only path overwrites this
  // with placeholder bodies; the success path overwrites via the loop's
  // try-block. The initialiser is never observed by downstream code.
  let synthResult: SynthesisResponse = {
    contracts: [],
    sections: {
      "api-contracts": "(none)",
      "data-models": "(none)",
      invariants: "(none)",
      "test-surface": "(none)",
    },
    tokens: { inputTokens: 0, outputTokens: 0 },
  };
  let shellOnly = false;
  let shellOnlyMessage = "";
  // v0.42.0 (AC-1b) — set when synth() RESOLVED successfully but produced
  // empty / all-`(none)` sections (LLM 200 OK with no usable content). The
  // file write is skipped just like the throw path so existing content is
  // preserved.
  let emptySections = false;
  // v0.42.0 (AC-3) — retry-on-429 wrapper. One retry attempt max, gated by
  // `FORGE_SPEC_RETRY_ON_429` (0 = disabled, default 60s cap, cap-clamped).
  // SDK's `maxRetries: 0` (set in anthropic.ts) means this is THE only retry
  // layer — no SDK double-up.
  let synthThrew = false;
  let synthError: unknown = undefined;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      synthResult = await synth({
        storyId: input.storyId,
        evalReport: input.evalReport,
        diffSummary,
        vocabularyPrompt,
      });
      synthThrew = false;
      synthError = undefined;
      break;
    } catch (err) {
      synthThrew = true;
      synthError = err;
      // Retry conditions: cap > 0 AND this is the first attempt AND error
      // is a 429 RateLimitError. Everything else falls through to the
      // existing catch handling (AC-3b: retry-exhaustion → no-overwrite).
      const isRateLimit = err instanceof Anthropic.RateLimitError;
      if (retryOn429Cap > 0 && attempt === 0 && isRateLimit) {
        const retryAfterHeader = err.headers?.get("retry-after");
        const retryAfterSeconds = retryAfterHeader
          ? Number.parseInt(retryAfterHeader, 10)
          : 0;
        // AC-5 — clamp to cap. Default 1s when header is missing / unparseable
        // so a header-less 429 still backs off briefly rather than hammering.
        const requestedSec =
          Number.isFinite(retryAfterSeconds) && retryAfterSeconds > 0
            ? retryAfterSeconds
            : 1;
        const sleepSec = Math.min(requestedSec, retryOn429Cap);
        await sleep(sleepSec * 1000);
        continue;
      }
      break;
    }
  }
  // After the retry loop: if synth succeeded, synthResult is set and
  // synthThrew=false. If it failed (initial throw + no retry, or
  // retry-exhausted), fall into the existing catch logic below.
  if (synthThrew) {
    const err = synthError;
    shellOnly = true;
    let raw = err instanceof Error ? err.message : String(err);

    // #548 (v0.40.7) — surface Anthropic's `retry-after` header on 429 so
    // operators know when it's safe to retry. The SDK exposes `RateLimitError`
    // (extends APIError<429, Headers>) with a `Headers` Web-API instance —
    // accessor is `.get('retry-after')` (NOT bracket-index — Headers is a
    // class, not a record).
    //
    // The header value per RFC 7231 §7.1.3 is either:
    //   - integer seconds (most common — Anthropic returns this shape)
    //   - HTTP-date (RFC 1123) — fallback parse
    //
    // We append the parsed/raw value to `raw` BEFORE the truncation step
    // so the suffix lives inside the warning's visible window.
    if (err instanceof Anthropic.RateLimitError) {
      const retryAfter = err.headers?.get("retry-after");
      if (retryAfter) {
        const seconds = Number.parseInt(retryAfter, 10);
        const suffix = Number.isFinite(seconds) && seconds > 0
          ? ` (retry after ${seconds}s)`
          : ` (retry after ${retryAfter})`;
        raw = `${raw}${suffix}`;
      }
    }

    shellOnlyMessage =
      raw.length > SHELL_ONLY_MESSAGE_MAX
        ? raw.slice(0, SHELL_ONLY_MESSAGE_MAX) + "…(truncated)"
        : raw;
    console.error(
      `spec-generator: synth() failed (continuing with shell-only placeholder body): ${raw}`,
    );
    synthResult = {
      contracts: [],
      sections: {
        "api-contracts": SHELL_ONLY_PLACEHOLDER_BODY,
        "data-models": SHELL_ONLY_PLACEHOLDER_BODY,
        invariants: SHELL_ONLY_PLACEHOLDER_BODY,
        "test-surface": SHELL_ONLY_PLACEHOLDER_BODY,
      },
      tokens: { inputTokens: 0, outputTokens: 0 },
    };
  } else {
    // v0.42.0 (AC-1b) — empty-sections detection on the success path. If the
    // LLM returned 200 OK but `defaultSynthesize` defaulted EVERY section to
    // `"(none)"` (because parsed.sections was empty / malformed / all-empty
    // strings), the spec-generator MUST NOT overwrite existing TECHNICAL-SPEC
    // content with `(none)` lines. The synth call succeeded but produced
    // nothing usable; treat that as a soft failure that preserves prior content.
    //
    // Distinguished from the LEGIT case where the LLM intentionally emits
    // `(none)` for ONE section but real content for the other three — that
    // flows through normally and DOES overwrite. The discriminator: ALL FOUR
    // sections are exactly `"(none)"` (case-sensitive).
    const allNone = REQUIRED_SECTIONS.every(
      (k) => (synthResult!.sections[k] ?? "").trim() === "(none)",
    );
    if (allNone) {
      emptySections = true;
    }
  }

  // Strategy 2: post-validate against the vocabulary. Strips bullets whose
  // backtick-quoted identifiers are not present in vocab (mode=strip), or
  // logs warnings without stripping (mode=warn). Skip entirely when the
  // vocabulary is empty (no source files to ground on) — every bullet would
  // be a false positive.
  let validatedSections = synthResult.sections;
  let warnings: SpecGeneratorWarning[] = [];
  const hasVocab = vocab.identifiers.size > 0 || vocab.testNames.size > 0;
  if (hasVocab) {
    const validated = validateAgainstVocabulary(
      synthResult.sections,
      vocab,
      { filesScanned: vocab.filesScanned.length },
    );
    validatedSections = validated.sections;
    warnings = validated.warnings;
  } else {
    // AC-8 lenient mode: no source vocabulary to ground on. Spec writes
    // verbatim (no strips). Emit one informational warning so consumers can
    // tell "validator skipped" apart from "validator ran clean".
    warnings = [{ kind: "no-vocabulary", filesScanned: vocab.filesScanned.length }];
  }

  // I6 — append the `spec-gen-shell-only` warning when `synth()` threw. Same
  // emit point as `no-vocabulary` (validator-pass site) per the plan; this is
  // additive and orthogonal to existing warnings (e.g. when `no-vocabulary`
  // already fired because there was no source vocab to ground on, the
  // shell-only marker still belongs in the array — both signals are true).
  if (shellOnly) {
    warnings.push({ kind: "spec-gen-shell-only", message: shellOnlyMessage });

    // F6 (v0.40.5) — macOS-only diagnostic. When the run fell through to
    // shell-only on darwin, do a cheap exit-code-only probe of macOS
    // Keychain to distinguish "no creds at all" from "creds exist in
    // Keychain but forge can't read them" (locked, prompt-timeout, ACL
    // mismatch). The latter case gets a typed `spec-gen-creds-keychain-only`
    // warning telling the operator to set ANTHROPIC_API_KEY to bypass
    // (rather than the misleading "log in to Claude Code" advice — they
    // already are).
    //
    // Single-locus per F49: KEYCHAIN_SERVICE_NAME is imported from
    // anthropic.ts (the OAuth read locus) so the service-name string lives
    // at one source-of-truth.
    //
    // F45 escape: if the existence-probe ITSELF throws unexpectedly (not
    // just non-zero exit — e.g. /usr/bin/security missing on a stripped-down
    // macOS install), fall through to emitting only `spec-gen-shell-only`.
    // Loud failure preserved via the existing shell-only warning.
    //
    // #546 (v0.40.7) — narrowing gate. The keychain warning is meaningful
    // ONLY when the underlying synth() failure was auth-class. If the
    // failure was an HTTP 4xx (other than 401) or 5xx — e.g. 429 rate-limit,
    // 500 server error — credentials are FINE; the keychain probe would
    // emit a misleading "Keychain locked or ACL mismatched" warning that
    // sends the operator down the wrong diagnostic path.
    //
    // Anthropic SDK's `APIError.makeMessage` (verified at
    // node_modules/@anthropic-ai/sdk/core/error.js:18-29) returns
    // `${status} ${msg}` when both status and msg are truthy — so a real
    // 429 produces `err.message = "429 ..."`. The regex `^[45][0-9]{2}\b`
    // matches HTTP 4xx/5xx prefix (P64 producer/consumer seam asserted in
    // tests, F65 measurement-discipline grounded against the SDK source).
    //
    // 401 (AuthenticationError) is excluded from suppression because it IS
    // auth-class — the keychain probe IS meaningful for 401. The regex
    // matches all 4xx/5xx including 401, so we explicitly carve 401 out
    // below to preserve the original F6 path.
    const isHttp4xxOr5xx = /^[45][0-9]{2}\b/.test(shellOnlyMessage);
    const is401 = /^401\b/.test(shellOnlyMessage);
    const suppressKeychainProbe = isHttp4xxOr5xx && !is401;
    if (process.platform === "darwin" && !suppressKeychainProbe) {
      let keychainEntryExists = false;
      // #546 / v0.41.1 — P64 injection seam. Default to real execFileSync;
      // tests pass `input.execFileSyncFn` to deterministically simulate
      // entry-exists (success return) or entry-absent (throw).
      const execFile = input.execFileSyncFn ?? execFileSync;
      try {
        execFile(
          "/usr/bin/security",
          ["find-generic-password", "-s", KEYCHAIN_SERVICE_NAME, "-a", userInfo().username],
          { stdio: "ignore", timeout: 1000 },
        );
        // Exit 0 → entry exists. Our reader couldn't get a usable token
        // from it (else we wouldn't be in shellOnly), so creds are
        // present-but-unreadable.
        keychainEntryExists = true;
      } catch {
        // Non-zero exit OR probe itself threw → entry truly missing or
        // unprobable. Emit only spec-gen-shell-only (existing behavior).
      }
      if (keychainEntryExists) {
        warnings.push({
          kind: "spec-gen-creds-keychain-only",
          message:
            `macOS Keychain entry exists for "${KEYCHAIN_SERVICE_NAME}" but forge-harness ` +
            `could not read it (locked, prompt-timeout, or ACL mismatch). ` +
            `Set ANTHROPIC_API_KEY to bypass.`,
        });
      }
    }
  }

  // v0.42.0 (AC-1b) — emit `spec-gen-empty-sections` warning when synth
  // succeeded but produced no usable content. Companion to the no-write gate
  // below; this is the loud-failure surface so consumers see WHY the file
  // wasn't refreshed.
  if (emptySections) {
    warnings.push({
      kind: "spec-gen-empty-sections",
      message:
        "synth() resolved with empty / all-(none) sections; existing TECHNICAL-SPEC content preserved",
    });
  }

  // v0.42.0 (AC-1 / AC-1b / P34 Strict Output Contract) — when synth failed
  // OR returned empty sections, SKIP the merge + write entirely. Existing
  // content is preserved; warnings already surface the cause. Loud failure
  // (warnings) is always better than silent corruption (placeholder
  // overwrite). The pre-v0.42.0 path overwrote real content with
  // `SHELL_ONLY_PLACEHOLDER_BODY` and was the silent-data-loss bug fixed
  // here. Cairn-stone: F-FORGE-SPEC-GEN-OVERWRITES-ON-SYNTH-FAILURE.
  const preserveExistingOnSynthFailure = shellOnly || emptySections;
  if (preserveExistingOnSynthFailure) {
    return {
      specPath,
      genTimestamp: now,
      genTokens: synthResult.tokens,
      contracts: synthResult.contracts,
      bodyChanged: false,
      warnings,
    };
  }

  // Merge into front-matter `stories[]` by id.
  const idx = parsed.frontMatter.stories.findIndex((s) => s.id === input.storyId);
  const entry = { id: input.storyId, lastUpdated: now, lastGitSha: gitShaSafe };
  if (idx === -1) parsed.frontMatter.stories.push(entry);
  else parsed.frontMatter.stories[idx] = entry;
  // Sort by id for byte-stable output.
  parsed.frontMatter.stories.sort((a, b) => a.id.localeCompare(b.id));
  parsed.frontMatter.lastUpdated = now;
  parsed.frontMatter.schemaVersion = SCHEMA_VERSION;

  // Rebuild body: replace any existing `## story: <id>` block, otherwise
  // append. The current body may contain multiple sections; we walk them.
  const newSection = renderStorySection(input.storyId, validatedSections);
  const bodyChanged = mergeStorySectionInBody(parsed, input.storyId, newSection);

  // Write atomically. Prepend the Bundle 1a agent-first header (5 HTML
  // comments + blank line) and the visible "Generated by ..." line so any
  // agent who opens the file sees its purpose, regeneration policy, and
  // last-refresh date in the first 7 lines. The date line uses today's
  // calendar date (UTC); the comment block is byte-identical across regens
  // per AC-1a-3.
  mkdirSync(dirname(specPath), { recursive: true });
  const today = now.slice(0, 10);
  const headerBlock = [
    ...AGENT_FIRST_COMMENT_BLOCK,
    "",
    `> Generated by forge-harness on ${today}.`,
    "",
  ].join("\n");
  const out = `${headerBlock}\n---\n${renderFrontMatter(parsed.frontMatter)}\n---\n\n${normaliseBody(parsed.body)}`;
  // W3 (#514): skip the write if the existing file already represents the
  // same logical state (ignoring the daily date line and the `lastUpdated:`
  // timestamps). Eliminates per-PASS dated-banner churn in consumer repos.
  // Preserves AC-1a-3 byte-stability of the agent-first comment block.
  idempotentWrite(specPath, out);

  return {
    specPath,
    genTimestamp: now,
    genTokens: synthResult.tokens,
    contracts: synthResult.contracts,
    bodyChanged,
    warnings,
  };
}

function emptySpec(timestamp: string): ParsedSpec {
  return {
    frontMatter: {
      schemaVersion: SCHEMA_VERSION,
      lastUpdated: timestamp,
      stories: [],
    },
    body: "",
  };
}

/**
 * In-place: replace or append the `## story: <id>` block in `parsed.body`.
 * Returns true if a textually different block was written (a write that only
 * updates `lastUpdated` may still produce identical body; the front-matter
 * mutation is what the spec sees in that case).
 */
function mergeStorySectionInBody(
  parsed: ParsedSpec,
  storyId: string,
  newSection: string,
): boolean {
  const sections = splitBodyByStory(parsed.body);
  let replaced = false;
  let bodyChanged = false;
  const merged: string[] = [];
  for (const s of sections) {
    if (s.id === storyId) {
      if (s.markdown.trim() !== newSection.trim()) bodyChanged = true;
      merged.push(newSection);
      replaced = true;
    } else {
      merged.push(s.markdown);
    }
  }
  if (!replaced) {
    merged.push(newSection);
    bodyChanged = true;
  }
  // Sort the story sections by id for byte-stable output, preserving any
  // free-floating non-story `## ...` blocks at the top.
  const storyChunks = merged.filter((m) => /^## story: /.test(m));
  const otherChunks = merged.filter((m) => !/^## story: /.test(m));
  storyChunks.sort((a, b) => {
    const aId = a.match(/^## story: (\S.*)/)?.[1] ?? "";
    const bId = b.match(/^## story: (\S.*)/)?.[1] ?? "";
    return aId.localeCompare(bId);
  });
  // W4 (#515): trim ALL trailing whitespace (newlines and spaces) from each
  // chunk before joining so the `"\n\n"` join produces exactly one blank line
  // between adjacent sections — never two or three. Without this, sections
  // that already ended with a trailing blank line stack with the join's two
  // newlines to produce `\n\n\n` (a triple-blank-line gap), and re-rendering
  // a story section perturbs the bytes of OTHER (unrelated) story sections.
  const trim = (chunk: string) => chunk.replace(/\s+$/, "");
  parsed.body = [...otherChunks, ...storyChunks].map(trim).join("\n\n").trim();
  return bodyChanged;
}

function normaliseBody(body: string): string {
  return body.replace(/\r\n/g, "\n").trim() + "\n";
}
